### ISSUE TITLE
프레젠테이션 준비 및 상세 기능 의논

### ISSUE THREAD

**Issue by lixxce5017** [lixxce5017/cbun-industry#1]
주식분석 및 자동매매를 기반으로 주식에 대한 어플을 만들기로 
우리 정하였습니다. 세부 기능 및 교수님이 말씀하신 저희만의 차별점에 대해 
의논해보자.

**Comment by lixxce5017** [comment]
![Uploading R.png…]()

**Comment by cbnucomp** [comment]
종목을 검색하면 동종업계나 라이벌업계의 주가를 비교하는것도 좋은것 같아요
ex) 삼성전자를 검색시 LG나 애플과 같은 동종업계들을 보여주는 프로그램 구현

**Comment by lixxce5017** [comment]
비트코인에 대해서는 어찌 생각하는가? 
비트코인은 이미 업비트에 너무 많은 것이 구현되어 있다.

**Comment by cbnucomp** [comment]
자동매매나 자동매도의 경우 이미 구현된 프로그램들이 많이 있어서 차별점이 꼭 필요한것 같아요

**Comment by cbnucomp** [comment]
주식장 개장 시작이나 폐장시간을 알림으로 알려주는 기능도 있으면 좋을것 같아요

**Comment by cbnucomp** [comment]
과도한 투자를 방지하기 위해 사전에 정해놓은 일정 금액을 초과하여 투자하려고 시도할 경우 경고하거나 거래를 막는 기능도 좋아보여요

**Comment by lixxce5017** [comment]
너는 굉장히 똑똑한  것 같다 ! 

> 과도한 투자를 방지하기 위해 사전에 정해놓은 일정 금액을 초과하여 투자하려고 시도할 경우 경고하거나 거래를 막는 기능도 좋아보여요

오ㅓ 똑똑하ㅓ네 그리고 나 또 떠올랐어
ai가 추천해주는 기능들은 어떨까`??

**Comment by lixxce5017** [comment]
교수님에게 빠꾸 당할 시 비트코인 주식은 너무 이미 어플 프로그램이 많으니 부동산에 관련한 것도 괜찮아 보인다.
어차피  이 수업으로 만들 프로그램은 관찰이 주 내용 아닌가?
예시로 금은방 도둑 들듯이.

**Comment by cbnucomp** [comment]
> 너는 굉장히 똑똑한 것 같다 !
> 
> > 과도한 투자를 방지하기 위해 사전에 정해놓은 일정 금액을 초과하여 투자하려고 시도할 경우 경고하거나 거래를 막는 기능도 좋아보여요
> 
> 오ㅓ 똑똑하ㅓ네 그리고 나 또 떠올랐어 ai가 추천해주는 기능들은 어떨까`??

추천하는 기능도 좋긴한데 투자가 성공적이지 못했을 경우 누군가는 책임을 져여하는 상황이 생기는데 AI가 추천하는 경우에는 책임소재가 불분명하기 때문에 사전에 책임지지 않는다는 경고를 하거나 추천보다는 그냥 사용자가 참고할 수 있도록 화면에 표시만 해주는 방향이 더 나을것 같아요
