### ISSUE TITLE
특허 보고서 작성은 누가하는게 좋을까요?

### ISSUE THREAD

**Issue by cbnucomp** [lixxce5017/cbun-industry#10]

**Comment by cbnucomp** [comment]
저희 전부 다 처음 해보는거여서 다같이 모여서 작성하는건 어떨까요?

**Comment by lixxce5017** [comment]
> 저희 전부 다 처음 해보는거여서 다같이 모여서 작성하는건 어떨까요?

좋아요~ 이따 7시에 보기로 한대로 일단 그 쪽 집에서 회의 하고  바로 하는건 어떨까요?
