### ISSUE TITLE
푸시 강제로 할 시 기존 커밋 날라갈 수 있습니다 주의

### ISSUE THREAD

**Issue by lixxce5017** [lixxce5017/cbun-industry#18]
전 다 날라갔습니다 .
50%의 확률로 다 날라간다는데 다들 푸쉬하시더라도
checkout 하셔서 로컬에서 바꾸고 강제푸쉬 하세요 
조심 앵간하면 쓰지마삼

**Comment by cbnucomp** [comment]
아이고..안타깝네요ㅋㅋㅋㅋ

**Comment by Indwoo** [comment]
ㅋㅋㅋㅋㅋㅋㅋ 확인확인
