### ISSUE TITLE
 주식 차트 구현 pyqtgraph VS OHLC VS Candle stick

### ISSUE THREAD

**Issue by lixxce5017** [lixxce5017/cbun-industry#22]
뭐가 좋을까요 계속 보고 있는데 
감이 안 오네요

**Comment by Indwoo** [comment]
pyqt가 제일 무난하지 않을까? Candle stick은 처음 들어보는데

**Comment by cbnucomp** [comment]
저도 pyqt가 적절것 같아요. 아무래도 시간이 부족해서 알고있는걸로 구현하는게 맞다고 봅니다!
