### ISSUE TITLE
KoaStudio 설치시 오류 해결방법

### ISSUE THREAD

**Issue by lixxce5017** [lixxce5017/cbun-industry#23]
위 에러는 KOA StudioSA라는 프로그램의 C++로 개발되어있는데 이를 실행하는데 필요한 요소들이 여러분의 컴퓨터에 없어서 발생하는 겁니다. 에러가 발생한다면 KOA StudioSA.exe 파일을 C:/OpenAPI 디렉토리로 복사한 후 해당 디렉토리에서 실행해보시기 바립니다

인터넷에 사진 첨부가 안되는데 저렇게 하면됨

 오류 :mfc,1000.dll 코드가 없어 실행 시킬 수 없습니다.
프로그램을 다시  설치하면 이 문제가 해결될 수 있습니다

**Comment by cbnucomp** [comment]
헉 해결했습니다~ㅎㅎ
