### ISSUE TITLE
kiwoom 파일 지우고 commit 다 다시 올리기 끝

### ISSUE THREAD

**Issue by lixxce5017** [lixxce5017/cbun-industry#38]
monitorig 등 다른 파일은 냅뒀습니다.
kiwoom도 결과적을 ㅗ바뀐 건 없고
마스터에 있는  커밋 못 가져와서 교수님이
다시 지우고 커밋하라 하셔서요ㅡ

**Comment by Indwoo** [comment]
ㅋㅋㅋㅋㅋㅋ 수고했으
