### ISSUE TITLE
중간발표 ppt에 어떤 내용이 들어가면 좋을까요?

### ISSUE THREAD

**Issue by cbnucomp** [lixxce5017/cbun-industry#4]

**Comment by Indwoo** [comment]
우선 요구사항인 problem, Input-Output, 차별성, solution은 필수로 포함하자

**Comment by lixxce5017** [comment]
우르의 차별점이 좀 부족 한 것 같아요. 어떻게 생각하시죠?

**Comment by cbnucomp** [comment]
저도 차별점이 좀 부족한것 같아요 발표할때 더 자세히 설명해주셔야 할 것 같아요!

**Comment by Indwoo** [comment]
차별점은 편리성하고 효율점 위주로 생각하자
