### ISSUE TITLE
앞으로의 개발 현황

### ISSUE THREAD

**Issue by lixxce5017** [lixxce5017/cbun-industry#5]
우리가 기초 현재 기초적인 UI만 구현을 했습니다.
시험이 끝난 뒤 어느 부분의 
요구사항 부분 부터 작업을 하는 것이 효율적일까요??

**Comment by cbnucomp** [comment]
우선 키움증권에서 사용자 정보를 받아오는게 우선적으로 하는게 어떤가요?

**Comment by lixxce5017** [comment]
그게 좋겠네 키움증권  api는 금융계좌를 만들어야 하는데 각자 다음주까지 만들어 놓자

**Comment by lixxce5017** [comment]
형 그럼 이제 뭐 하는게 좋을까 먼저 차트 랜더링부터 어떄?

**Comment by Indwoo** [comment]
계좌 만들 때 모르는 거 있으면 물어보고 UI 끝나면 렌더링 들어가자
