### ISSUE TITLE
멘토 조언대로 키움증권 쓸까요 한국투자증권 api 쓸 까요?

### ISSUE THREAD

**Issue by lixxce5017** [lixxce5017/cbun-industry#8]
??

**Comment by cbnucomp** [comment]
원래 예정대로 키움증권으로 하는게 좋지 않을까요?
한국투자증권으로 바꾸면 방향을 완전 트는 느낌이네요

**Comment by lixxce5017** [comment]
> 원래 예정대로 키움증권으로 하는게 좋지 않을까요? 한국투자증권으로 바꾸면 방향을 완전 트는 느낌이네요

아 저도 그렇게 생각해요~! 그럼 저희의 계획과 좀 달라지고 너무 어려워지네요~
