### ISSUE TITLE
차트 렌더링 방식

### ISSUE THREAD

**Issue by cbnucomp** [lixxce5017/cbun-industry#9]
멘토님께서 pyqt의 pyqtgraph를 이용하여 실시간 차트 렌더링을 추천해주셨는데 이를 반영할까요?

**Comment by cbnucomp** [comment]
실시간성을 고려하여 pyqtgraph를 활용하는것이 좋을 것 같다는 말씀을 하셨습니다

**Comment by lixxce5017** [comment]
> 멘토님께서 pyqt의 pyqtgraph를 이용하여 실시간 차트 렌더링을 추천해주셨는데 이를 반영할까요?

원래는 리액트로 해볼려 했는데 이게 설명해주신 대로 좀 더 쉽고 굳이 백엔드까지 구현 안해도 된다고 하셨으니 이게 더 합리적이겠네요!!

**Comment by lixxce5017** [comment]
> 실시간성을 고려하여 pyqtgraph를 활용하는것이 좋을 것 같다는 말씀을 하셨습니다

동의합니다 !
